// Package migrate converts an existing sst.config.ts to sst.config.go.
// It handles the most common SST v3 patterns. For exotic patterns it emits
// a TODO comment so you know exactly what needs manual attention.
package migrate

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"unicode"
)

// Result is the output of a migration run.
type Result struct {
	GoSource    string   // Generated sst.config.go content
	Warnings    []string // Patterns that need manual review
	Unsupported []string // Patterns the migrator could not convert
}

// Convert parses tsSource (the content of an sst.config.ts) and returns
// the equivalent Go source + any warnings.
func Convert(tsSource string) (*Result, error) {
	m := &migrator{
		src:      tsSource,
		imports:  map[string]bool{},
		warnings: []string{},
		unsup:    []string{},
	}
	return m.run()
}

// ConvertFile is a convenience wrapper that reads the TS file from disk.
func ConvertFile(path string) (*Result, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return Convert(string(b))
}

// ── Migrator ──────────────────────────────────────────────────────────────────

type migrator struct {
	src      string
	imports  map[string]bool
	warnings []string
	unsup    []string
}

// run is the top-level conversion driver.
func (m *migrator) run() (*Result, error) {
	appCfg := m.extractAppConfig()
	runBody := m.extractRunBody()
	goRun := m.convertRunBody(runBody)

	removal := m.buildRemovalPolicy(appCfg)
	appName := appCfg["name"]
	if appName == "" {
		appName = "my-app"
		m.warnings = append(m.warnings, "Could not detect app name — defaulting to \"my-app\"")
	}

	// Build import list.
	importLines := []string{`"github.com/nimbus-local/forge"`}
	if m.imports["constructs"] {
		importLines = append(importLines, `"github.com/nimbus-local/forge/constructs"`)
	}

	src := fmt.Sprintf(`// Code generated by forge migrate — review TODOs before deploying.
package main

import (
	%s
)

func main() {
	forge.Run(&forge.Config{
		App: &forge.AppConfig{
			Name: %q,
			Home: "aws",
			%s},
		Run: func(ctx *forge.RunContext) error {
%s
			return nil
		},
	})
}
`,
		strings.Join(importLines, "\n\t"),
		appName,
		removal,
		goRun,
	)

	return &Result{
		GoSource:    src,
		Warnings:    m.warnings,
		Unsupported: m.unsup,
	}, nil
}

// ── App config extraction ─────────────────────────────────────────────────────

var configRe = regexp.MustCompile(`(?s)app\s*\([^)]*\)\s*\{.*?return\s*\{(.*?)\}`)
var kvRe = regexp.MustCompile(`(\w+)\s*:\s*([^,\n]+)`)

func (m *migrator) extractAppConfig() map[string]string {
	result := map[string]string{}
	match := configRe.FindStringSubmatch(m.src)
	if len(match) < 2 {
		return result
	}
	block := match[1]
	for _, kv := range kvRe.FindAllStringSubmatch(block, -1) {
		result[strings.TrimSpace(kv[1])] = strings.TrimSpace(kv[2])
	}
	return result
}

// buildRemovalPolicy converts the SST removal ternary to a Go Removal field.
func (m *migrator) buildRemovalPolicy(appCfg map[string]string) string {
	removal := appCfg["removal"]
	if removal == "" {
		return ""
	}
	// "retain" literal
	if strings.Contains(removal, `"retain"`) && !strings.Contains(removal, "?") {
		return `Removal: forge.RemovalRetain,` + "\n\t\t\t"
	}
	// common ternary: stage === "production" ? "retain" : "remove"
	if strings.Contains(removal, "?") {
		m.warnings = append(m.warnings, "Removal policy uses a conditional — converted to stage-based check; verify it matches your intent.")
		return `Removal: func() forge.RemovalPolicy {
				if ctx.Stage == "production" {
					return forge.RemovalRetain
				}
				return forge.RemovalDestroy
			}(),` + "\n\t\t\t"
	}
	return ""
}

// ── Run body extraction & conversion ─────────────────────────────────────────

// extractRunBody pulls out everything inside `async run() { ... }`.
var runBodyRe = regexp.MustCompile(`(?s)async\s+run\s*\(\s*\)\s*\{(.*)\}`)

func (m *migrator) extractRunBody() string {
	match := runBodyRe.FindStringSubmatch(m.src)
	if len(match) < 2 {
		return ""
	}
	// Trim the final `return { ... }` block — we handle exports separately.
	body := match[1]
	returnIdx := strings.LastIndex(body, "return {")
	exports := ""
	if returnIdx >= 0 {
		exports = body[returnIdx:]
		body = body[:returnIdx]
	}
	m.convertExports(exports)
	return strings.TrimSpace(body)
}

// convertRunBody iterates over lines and converts SST constructs to Go.
func (m *migrator) convertRunBody(body string) string {
	lines := strings.Split(body, "\n")
	var out []string

	for _, line := range lines {
		converted := m.convertLine(strings.TrimSpace(line))
		if converted != "" {
			out = append(out, "\t\t\t"+converted)
		}
	}
	return strings.Join(out, "\n")
}

// constructMap maps SST TS construct names to Go constructor names.
var constructMap = map[string]string{
	"sst.aws.Function":     "constructs.NewFunction",
	"sst.aws.ApiGatewayV2": "constructs.NewApiGatewayV2",
	"sst.aws.ApiGatewayV1": "constructs.NewApiGatewayV2", // upgrade
	"sst.aws.DynamoDB":     "constructs.NewDynamoDB",
	"sst.aws.Bucket":       "constructs.NewBucket",
	"sst.aws.Cron":         "constructs.NewCron",
	"sst.aws.Queue":        "constructs.NewQueue",
	"sst.aws.Topic":        "constructs.NewTopic",
	"sst.aws.StaticSite":   "constructs.NewStaticSite",
	"sst.aws.NextjsSite":   "constructs.NewNextjsSite",
}

// constructArgsMap maps SST construct names to their Go args struct.
var constructArgsMap = map[string]string{
	"sst.aws.Function":     "constructs.FunctionArgs",
	"sst.aws.ApiGatewayV2": "constructs.ApiGatewayV2Args",
	"sst.aws.DynamoDB":     "constructs.DynamoDBArgs",
	"sst.aws.Bucket":       "constructs.BucketArgs",
}

// newConstructRe matches: const varName = new sst.aws.Construct("Name", { ... });
// We handle single-line and note multi-line constructs in warnings.
var newConstructRe = regexp.MustCompile(`(?:const|let|var)\s+(\w+)\s*=\s*new\s+(sst\.\w+\.\w+)\s*\(\s*"([^"]+)"`)

// routeRe matches: api.route("METHOD /path", { handler: "..." })
var routeRe = regexp.MustCompile(`(\w+)\.route\s*\(\s*"([^"]+)"\s*,\s*\{([^}]*)\}`)

// simpleRouteRe matches: api.route("METHOD /path", fn)
var simpleRouteRe = regexp.MustCompile(`(\w+)\.route\s*\(\s*"([^"]+)"\s*,\s*(\w+)`)

func (m *migrator) convertLine(line string) string {
	if line == "" || strings.HasPrefix(line, "//") {
		return line
	}

	// ── new sst.aws.X("Name", {...}) ─────────────────────────────────────────
	if match := newConstructRe.FindStringSubmatch(line); len(match) == 4 {
		varName, tsType, constructName := match[1], match[2], match[3]
		goConstructor, ok := constructMap[tsType]
		if !ok {
			m.unsup = append(m.unsup, fmt.Sprintf("Unknown construct: %s", tsType))
			return fmt.Sprintf("// TODO: unsupported construct %s — %s", tsType, line)
		}

		m.imports["constructs"] = true
		goArgs, hasArgs := constructArgsMap[tsType]

		// Extract inline args (best-effort; multi-line requires manual fix).
		inlineArgs := extractInlineArgs(line)
		argsStr := m.convertArgs(tsType, inlineArgs)

		if hasArgs && argsStr != "" {
			return fmt.Sprintf(`%s := %s(ctx, %q, &%s{
				%s
			})`, varName, goConstructor, constructName, goArgs, argsStr)
		}
		return fmt.Sprintf(`%s := %s(ctx, %q, nil)`, varName, goConstructor, constructName)
	}

	// ── api.route("METHOD /path", { handler: "..." }) ────────────────────────
	if match := routeRe.FindStringSubmatch(line); len(match) == 4 {
		apiVar, routeKey, argsBlock := match[1], match[2], match[3]
		handler := extractQuotedValue(argsBlock, "handler")
		link := extractLinkValue(argsBlock)
		linkStr := ""
		if link != "" {
			linkStr = fmt.Sprintf("\n\t\t\t\tLink: []forge.Linkable{%s},", link)
		}
		return fmt.Sprintf(`%s.Route(%q, &constructs.RouteArgs{
				Handler: %q,%s
			})`, apiVar, routeKey, handler, linkStr)
	}

	// ── api.route("METHOD /path", fn) ────────────────────────────────────────
	if match := simpleRouteRe.FindStringSubmatch(line); len(match) == 4 {
		apiVar, routeKey, fnVar := match[1], match[2], match[3]
		return fmt.Sprintf(`%s.Route(%q, &constructs.RouteArgs{Function: %s})`, apiVar, routeKey, fnVar)
	}

	// ── Unrecognised line ─────────────────────────────────────────────────────
	if strings.Contains(line, "new sst.") || strings.Contains(line, ".route(") {
		m.warnings = append(m.warnings, fmt.Sprintf("Multi-line construct (review manually): %s", truncate(line, 60)))
		return "// TODO: review — " + line
	}

	return "// " + line // Comment out anything we don't understand
}

// convertExports handles `return { key: value.url }` → ctx.Export(...)
var exportKVRe = regexp.MustCompile(`(\w+)\s*:\s*([^,\n}]+)`)

func (m *migrator) convertExports(block string) {
	// TODO: emit ctx.Export() calls — stored in warnings for now
	for _, kv := range exportKVRe.FindAllStringSubmatch(block, -1) {
		key := strings.TrimSpace(kv[1])
		val := strings.TrimSpace(kv[2])
		// Strip .url, .arn etc — we can't resolve the Go equivalent here.
		m.warnings = append(m.warnings, fmt.Sprintf(
			"Add export manually: ctx.Export(%q, <construct>.URL()) for TS value: %s", key, val))
	}
}

// convertArgs does a best-effort conversion of inline TS args to Go struct fields.
func (m *migrator) convertArgs(tsType, inline string) string {
	if inline == "" {
		return ""
	}
	var fields []string

	switch tsType {
	case "sst.aws.Function":
		if h := extractQuotedValue(inline, "handler"); h != "" {
			fields = append(fields, fmt.Sprintf("Handler: %q,", h))
		}
		if rt := extractQuotedValue(inline, "runtime"); rt != "" {
			fields = append(fields, fmt.Sprintf("Runtime: %q,", rt))
		}
		if link := extractLinkValue(inline); link != "" {
			fields = append(fields, fmt.Sprintf("Link: []forge.Linkable{%s},", link))
		}

	case "sst.aws.DynamoDB":
		// Fields and primaryIndex are typically multi-line; emit TODO.
		m.warnings = append(m.warnings, "DynamoDB Fields/PrimaryIndex need manual conversion — see constructs.DynamoDBArgs")

	case "sst.aws.Bucket":
		if strings.Contains(inline, "public: true") {
			fields = append(fields, "Public: true,")
		}
	}

	return strings.Join(fields, "\n\t\t\t\t")
}

// ── Low-level helpers ─────────────────────────────────────────────────────────

var quotedValueRe = func(key string) *regexp.Regexp {
	return regexp.MustCompile(key + `\s*:\s*"([^"]+)"`)
}

func extractQuotedValue(s, key string) string {
	re := quotedValueRe(key)
	m := re.FindStringSubmatch(s)
	if len(m) < 2 {
		return ""
	}
	return m[1]
}

var linkRe = regexp.MustCompile(`link\s*:\s*\[([^\]]+)\]`)

func extractLinkValue(s string) string {
	m := linkRe.FindStringSubmatch(s)
	if len(m) < 2 {
		return ""
	}
	// "link: [table, bucket]" → "table, bucket"
	items := strings.Split(m[1], ",")
	var cleaned []string
	for _, item := range items {
		item = strings.TrimFunc(item, unicode.IsSpace)
		if item != "" {
			cleaned = append(cleaned, item)
		}
	}
	return strings.Join(cleaned, ", ")
}

var inlineArgsRe = regexp.MustCompile(`\{([^}]+)\}`)

func extractInlineArgs(line string) string {
	m := inlineArgsRe.FindStringSubmatch(line)
	if len(m) < 2 {
		return ""
	}
	return m[1]
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
